import { NextResponse } from "next/server";

export async function GET() {
  const packages = [
    {
      id: "autos",
      name: "Autos del Mundo",
      description: "Las marcas de vehículos más icónicas, veloces y prestigiosas.",
      icon: "🏎️",
      count: 17,
      marcas: [
        { id: "auto-ferrari", categoria: "Autos", nombre: "Ferrari", logoUrl: "/paquetes/ferrari.png" },
        { id: "auto-lamborghini", categoria: "Autos", nombre: "Lamborghini", logoUrl: "/paquetes/lamborghini.png" },
        { id: "auto-bugatti", categoria: "Autos", nombre: "Bugatti", logoUrl: "/paquetes/bugatti.png" },
        { id: "auto-mclaren", categoria: "Autos", nombre: "McLaren", logoUrl: "/paquetes/mclaren.png" },
        { id: "auto-aston-martin", categoria: "Autos", nombre: "Aston Martin", logoUrl: "/paquetes/aston-martin.png" },
        { id: "auto-maserati", categoria: "Autos", nombre: "Maserati", logoUrl: "/paquetes/maserati.png" },
        { id: "auto-bentley", categoria: "Autos", nombre: "Bentley", logoUrl: "/paquetes/bentley.png" },
        { id: "auto-rolls-royce", categoria: "Autos", nombre: "Rolls Royce", logoUrl: "/paquetes/rolls-royce.png" },
        { id: "auto-audi", categoria: "Autos", nombre: "Audi", logoUrl: "/paquetes/audi.png" },
        { id: "auto-lexus", categoria: "Autos", nombre: "Lexus", logoUrl: "/paquetes/lexus.png" },
        { id: "auto-jaguar", categoria: "Autos", nombre: "Jaguar", logoUrl: "/paquetes/jaguar.png" },
        { id: "auto-land-rover", categoria: "Autos", nombre: "Land Rover", logoUrl: "/paquetes/land-rover.png" },
        { id: "auto-nissan", categoria: "Autos", nombre: "Nissan", logoUrl: "/paquetes/nissan.png" },
        { id: "auto-ford", categoria: "Autos", nombre: "Ford", logoUrl: "/paquetes/ford.png" },
        { id: "auto-dodge", categoria: "Autos", nombre: "Dodge", logoUrl: "/paquetes/dodge.png" },
        { id: "auto-alfa-romeo", categoria: "Autos", nombre: "Alfa Romeo", logoUrl: "/paquetes/alfa-romeo.png" },
        { id: "auto-mazda", categoria: "Autos", nombre: "Mazda", logoUrl: "/paquetes/mazda.png" },
      ]
    },
    {
      id: "gaming",
      name: "Videojuegos",
      description: "Las consolas, estudios de desarrollo y plataformas más famosas del gaming.",
      icon: "🎮",
      count: 13,
      marcas: [
        { id: "game-sega", categoria: "Videojuegos", nombre: "Sega", logoUrl: "/paquetes/sega.png" },
        { id: "game-atari", categoria: "Videojuegos", nombre: "Atari", logoUrl: "/paquetes/atari.png" },
        { id: "game-ea", categoria: "Videojuegos", nombre: "EA", logoUrl: "/paquetes/ea.png" },
        { id: "game-ubisoft", categoria: "Videojuegos", nombre: "Ubisoft", logoUrl: "/paquetes/ubisoft.png" },
        { id: "game-activision", categoria: "Videojuegos", nombre: "Activision", logoUrl: "/paquetes/activision.png" },
        { id: "game-rockstar", categoria: "Videojuegos", nombre: "Rockstar Games", logoUrl: "/paquetes/rockstar-games.png" },
        { id: "game-epic", categoria: "Videojuegos", nombre: "Epic Games", logoUrl: "/paquetes/epic-games.png" },
        { id: "game-riot", categoria: "Videojuegos", nombre: "Riot Games", logoUrl: "/paquetes/riot-games.png" },
        { id: "game-blizzard", categoria: "Videojuegos", nombre: "Blizzard", logoUrl: "/paquetes/blizzard.png" },
        { id: "game-capcom", categoria: "Videojuegos", nombre: "Capcom", logoUrl: "/paquetes/capcom.png" },
        { id: "game-bandai", categoria: "Videojuegos", nombre: "Bandai Namco", logoUrl: "/paquetes/bandai-namco.png" },
        { id: "game-cdpr", categoria: "Videojuegos", nombre: "CD Projekt Red", logoUrl: "/paquetes/cd-projekt-red.png" },
        { id: "game-discord", categoria: "Videojuegos", nombre: "Discord", logoUrl: "/paquetes/discord.png" },
      ]
    },
    {
      id: "licores",
      name: "Cervezas y Licores",
      description: "Las bebidas más reconocidas y populares en bares de todo el planeta.",
      icon: "🍻",
      count: 15,
      marcas: [
        { id: "cerveza-corona", categoria: "Licores", nombre: "Corona", logoUrl: "/paquetes/corona.png" },
        { id: "cerveza-heineken", categoria: "Licores", nombre: "Heineken", logoUrl: "/paquetes/heineken.png" },
        { id: "cerveza-guinness", categoria: "Licores", nombre: "Guinness", logoUrl: "/paquetes/guinness.png" },
        { id: "cerveza-budweiser", categoria: "Licores", nombre: "Budweiser", logoUrl: "/paquetes/budweiser.png" },
        { id: "cerveza-stella", categoria: "Licores", nombre: "Stella Artois", logoUrl: "/paquetes/stella-artois.png" },
        { id: "cerveza-modelo", categoria: "Licores", nombre: "Modelo", logoUrl: "/paquetes/modelo.png" },
        { id: "licor-jack", categoria: "Licores", nombre: "Jack Daniels", logoUrl: "/paquetes/jack-daniels.png" },
        { id: "licor-johnnie", categoria: "Licores", nombre: "Johnnie Walker", logoUrl: "/paquetes/johnnie-walker.png" },
        { id: "licor-bacardi", categoria: "Licores", nombre: "Bacardi", logoUrl: "/paquetes/bacardi.png" },
        { id: "licor-absolut", categoria: "Licores", nombre: "Absolut", logoUrl: "/paquetes/absolut.png" },
        { id: "licor-patron", categoria: "Licores", nombre: "Patron", logoUrl: "/paquetes/patron.png" },
        { id: "licor-jameson", categoria: "Licores", nombre: "Jameson", logoUrl: "/paquetes/jameson.png" },
        { id: "licor-grey", categoria: "Licores", nombre: "Grey Goose", logoUrl: "/paquetes/grey-goose.png" },
        { id: "licor-jager", categoria: "Licores", nombre: "Jagermeister", logoUrl: "/paquetes/jagermeister.png" },
        { id: "licor-don", categoria: "Licores", nombre: "Don Julio", logoUrl: "/paquetes/don-julio.png" },
      ]
    },
    {
      id: "aerolineas",
      name: "Aerolíneas",
      description: "Las compañías de aviación más icónicas para viajar por el mundo.",
      icon: "✈️",
      count: 9,
      marcas: [
        { id: "aero-emirates", categoria: "Aerolíneas", nombre: "Emirates", logoUrl: "/paquetes/emirates.png" },
        { id: "aero-delta", categoria: "Aerolíneas", nombre: "Delta", logoUrl: "/paquetes/delta.png" },
        { id: "aero-united", categoria: "Aerolíneas", nombre: "United", logoUrl: "/paquetes/united.png" },
        { id: "aero-lufthansa", categoria: "Aerolíneas", nombre: "Lufthansa", logoUrl: "/paquetes/lufthansa.png" },
        { id: "aero-klm", categoria: "Aerolíneas", nombre: "KLM", logoUrl: "/paquetes/klm.png" },
        { id: "aero-qantas", categoria: "Aerolíneas", nombre: "Qantas", logoUrl: "/paquetes/qantas.png" },
        { id: "aero-aeromexico", categoria: "Aerolíneas", nombre: "Aeromexico", logoUrl: "/paquetes/aeromexico.png" },
        { id: "aero-copa", categoria: "Aerolíneas", nombre: "Copa Airlines", logoUrl: "/paquetes/copa-airlines.png" },
        { id: "aero-ryanair", categoria: "Aerolíneas", nombre: "Ryanair", logoUrl: "/paquetes/ryanair.png" },
      ]
    },
    {
      id: "comida-rapida",
      name: "Comida Rápida",
      description: "Las cadenas de comida rápida más famosas del mundo.",
      icon: "🍔",
      count: 10,
      marcas: [
        { id: "fast-wendys", categoria: "Comida Rápida", nombre: "Wendys", logoUrl: "/paquetes/wendys.png" },
        { id: "fast-tacobell", categoria: "Comida Rápida", nombre: "Taco Bell", logoUrl: "/paquetes/taco-bell.png" },
        { id: "fast-innout", categoria: "Comida Rápida", nombre: "In-N-Out", logoUrl: "/paquetes/in-n-out.png" },
        { id: "fast-chipotle", categoria: "Comida Rápida", nombre: "Chipotle", logoUrl: "/paquetes/chipotle.png" },
        { id: "fast-shake", categoria: "Comida Rápida", nombre: "Shake Shack", logoUrl: "/paquetes/shake-shack.png" },
        { id: "fast-sonic", categoria: "Comida Rápida", nombre: "Sonic", logoUrl: "/paquetes/sonic.png" },
        { id: "fast-arbys", categoria: "Comida Rápida", nombre: "Arbys", logoUrl: "/paquetes/arbys.png" },
        { id: "fast-panda", categoria: "Comida Rápida", nombre: "Panda Express", logoUrl: "/paquetes/panda-express.png" },
        { id: "fast-krispy", categoria: "Comida Rápida", nombre: "Krispy Kreme", logoUrl: "/paquetes/krispy-kreme.png" },
        { id: "fast-carls", categoria: "Comida Rápida", nombre: "Carls Jr", logoUrl: "/paquetes/carls-jr.png" },
      ]
    },
    {
      id: "futbol",
      name: "Equipos de Fútbol",
      description: "Los clubes más grandes e históricos del deporte rey.",
      icon: "⚽",
      count: 13,
      marcas: [
        { id: "fut-realmadrid", categoria: "Fútbol", nombre: "Real Madrid", logoUrl: "/paquetes/real-madrid.png" },
        { id: "fut-barcelona", categoria: "Fútbol", nombre: "Barcelona", logoUrl: "/paquetes/barcelona.png" },
        { id: "fut-manutd", categoria: "Fútbol", nombre: "Manchester United", logoUrl: "/paquetes/manchester-united.png" },
        { id: "fut-psg", categoria: "Fútbol", nombre: "PSG", logoUrl: "/paquetes/psg.png" },
        { id: "fut-bayern", categoria: "Fútbol", nombre: "Bayern Munich", logoUrl: "/paquetes/bayern-munich.png" },
        { id: "fut-juve", categoria: "Fútbol", nombre: "Juventus", logoUrl: "/paquetes/juventus.png" },
        { id: "fut-chelsea", categoria: "Fútbol", nombre: "Chelsea", logoUrl: "/paquetes/chelsea.png" },
        { id: "fut-liverpool", categoria: "Fútbol", nombre: "Liverpool", logoUrl: "/paquetes/liverpool.png" },
        { id: "fut-arsenal", categoria: "Fútbol", nombre: "Arsenal", logoUrl: "/paquetes/arsenal.png" },
        { id: "fut-mancity", categoria: "Fútbol", nombre: "Manchester City", logoUrl: "/paquetes/manchester-city.png" },
        { id: "fut-milan", categoria: "Fútbol", nombre: "AC Milan", logoUrl: "/paquetes/ac-milan.png" },
        { id: "fut-inter", categoria: "Fútbol", nombre: "Inter Milan", logoUrl: "/paquetes/inter-milan.png" },
        { id: "fut-boca", categoria: "Fútbol", nombre: "Boca Juniors", logoUrl: "/paquetes/boca-juniors.png" },
      ]
    },
    {
      id: "relojes",
      name: "Relojes de Lujo",
      description: "Elegancia y precisión con las mejores marcas relojeras.",
      icon: "⌚",
      count: 10,
      marcas: [
        { id: "reloj-rolex", categoria: "Relojes", nombre: "Rolex", logoUrl: "/paquetes/rolex.png" },
        { id: "reloj-omega", categoria: "Relojes", nombre: "Omega", logoUrl: "/paquetes/omega.png" },
        { id: "reloj-tag", categoria: "Relojes", nombre: "Tag Heuer", logoUrl: "/paquetes/tag-heuer.png" },
        { id: "reloj-patek", categoria: "Relojes", nombre: "Patek Philippe", logoUrl: "/paquetes/patek-philippe.png" },
        { id: "reloj-casio", categoria: "Relojes", nombre: "Casio", logoUrl: "/paquetes/casio.png" },
        { id: "reloj-breitling", categoria: "Relojes", nombre: "Breitling", logoUrl: "/paquetes/breitling.png" },
        { id: "reloj-hublot", categoria: "Relojes", nombre: "Hublot", logoUrl: "/paquetes/hublot.png" },
        { id: "reloj-cartier", categoria: "Relojes", nombre: "Cartier", logoUrl: "/paquetes/cartier.png" },
        { id: "reloj-audemars", categoria: "Relojes", nombre: "Audemars Piguet", logoUrl: "/paquetes/audemars-piguet.png" },
        { id: "reloj-fossil", categoria: "Relojes", nombre: "Fossil", logoUrl: "/paquetes/fossil.png" },
      ]
    },
    {
      id: "bancos",
      name: "Bancos y Finanzas",
      description: "Instituciones financieras, tarjetas de crédito y bancos globales.",
      icon: "🏦",
      count: 7,
      marcas: [
        { id: "banco-chase", categoria: "Finanzas", nombre: "Chase", logoUrl: "/paquetes/chase.png" },
        { id: "banco-boa", categoria: "Finanzas", nombre: "Bank of America", logoUrl: "/paquetes/bank-of-america.png" },
        { id: "banco-santander", categoria: "Finanzas", nombre: "Santander", logoUrl: "/paquetes/santander.png" },
        { id: "banco-citi", categoria: "Finanzas", nombre: "Citi", logoUrl: "/paquetes/citi.png" },
        { id: "banco-hsbc", categoria: "Finanzas", nombre: "HSBC", logoUrl: "/paquetes/hsbc.png" },
        { id: "banco-barclays", categoria: "Finanzas", nombre: "Barclays", logoUrl: "/paquetes/barclays.png" },
        { id: "banco-morgan", categoria: "Finanzas", nombre: "Morgan Stanley", logoUrl: "/paquetes/morgan-stanley.png" },
      ]
    },
    {
      id: "streaming",
      name: "Streaming y Cine",
      description: "Las plataformas donde ves tus series y películas favoritas.",
      icon: "🍿",
      count: 13,
      marcas: [
        { id: "stream-disney", categoria: "Streaming", nombre: "Disney Plus", logoUrl: "/paquetes/disney-plus.png" },
        { id: "stream-hbo", categoria: "Streaming", nombre: "HBO Max", logoUrl: "/paquetes/hbo-max.png" },
        { id: "stream-marvel", categoria: "Streaming", nombre: "Marvel", logoUrl: "/paquetes/marvel.png" },
        { id: "stream-pixar", categoria: "Streaming", nombre: "Pixar", logoUrl: "/paquetes/pixar.png" },
        { id: "stream-prime", categoria: "Streaming", nombre: "Prime Video", logoUrl: "/paquetes/prime-video.png" },
        { id: "stream-crunchy", categoria: "Streaming", nombre: "Crunchyroll", logoUrl: "/paquetes/crunchyroll.png" },
        { id: "stream-appletv", categoria: "Streaming", nombre: "Apple TV", logoUrl: "/paquetes/apple-tv.png" },
        { id: "stream-peacock", categoria: "Streaming", nombre: "Peacock", logoUrl: "/paquetes/peacock.png" },
        { id: "stream-discovery", categoria: "Streaming", nombre: "Discovery", logoUrl: "/paquetes/discovery.png" },
        { id: "stream-universal", categoria: "Streaming", nombre: "Universal", logoUrl: "/paquetes/universal.png" },
        { id: "stream-warner", categoria: "Streaming", nombre: "Warner Bros", logoUrl: "/paquetes/warner-bros.png" },
        { id: "stream-dream", categoria: "Streaming", nombre: "DreamWorks", logoUrl: "/paquetes/dreamworks.png" },
        { id: "stream-lucas", categoria: "Streaming", nombre: "Lucasfilm", logoUrl: "/paquetes/lucasfilm.png" },
      ]
    },
    {
      id: "supermercados",
      name: "Supermercados",
      description: "Donde el mundo hace sus compras del hogar.",
      icon: "🛒",
      count: 4,
      marcas: [
        { id: "super-whole", categoria: "Supermercados", nombre: "Whole Foods", logoUrl: "/paquetes/whole-foods.png" },
        { id: "super-tesco", categoria: "Supermercados", nombre: "Tesco", logoUrl: "/paquetes/tesco.png" },
        { id: "super-kroger", categoria: "Supermercados", nombre: "Kroger", logoUrl: "/paquetes/kroger.png" },
        { id: "super-publix", categoria: "Supermercados", nombre: "Publix", logoUrl: "/paquetes/publix.png" },
      ]
    },
    {
      id: "audio",
      name: "Instrumentos y Audio",
      description: "Las mejores marcas para músicos y audiófilos.",
      icon: "🎸",
      count: 5,
      marcas: [
        { id: "audio-yamaha", categoria: "Audio", nombre: "Yamaha", logoUrl: "/paquetes/yamaha.png" },
        { id: "audio-jbl", categoria: "Audio", nombre: "JBL", logoUrl: "/paquetes/jbl.png" },
        { id: "audio-beats", categoria: "Audio", nombre: "Beats", logoUrl: "/paquetes/beats.png" },
        { id: "audio-marshall", categoria: "Audio", nombre: "Marshall", logoUrl: "/paquetes/marshall.png" },
        { id: "audio-harman", categoria: "Audio", nombre: "Harman Kardon", logoUrl: "/paquetes/harman-kardon.png" },
      ]
    },
    {
      id: "belleza",
      name: "Cosméticos y Belleza",
      description: "El glamour de la mano de las empresas de moda y maquillaje.",
      icon: "💄",
      count: 3,
      marcas: [
        { id: "belleza-nyx", categoria: "Cosméticos", nombre: "Nyx", logoUrl: "/paquetes/nyx.png" },
        { id: "belleza-urban", categoria: "Cosméticos", nombre: "Urban Decay", logoUrl: "/paquetes/urban-decay.png" },
        { id: "belleza-avon", categoria: "Cosméticos", nombre: "Avon", logoUrl: "/paquetes/avon.png" },
      ]
    },
  ];

  return NextResponse.json({ packages });
}
